approve_by_comment: true
approve_regex: ^LGTM
reject_regex: ^Rejected
reset_on_push: true
author_approval: ignored
signed_off_by:
  required: true
reviewers:
  teams:
  - release
  name: default
  required: 1
